/**
 * Pure operations on `visit.doClaims` and their steps. Never mutate; ids and
 * dates are provided by the caller (the autosave replays these functions):
 * `createDoClaim` receives the ids of its 10 steps, `setStepStatus` receives
 * today's date.
 */
import { isValidIsoDate } from '@/lib/dates'
import { cleanOptional, insertAt, withOptional } from '@/lib/objects'
import type { DoClaim, DoStep, DoStepStatus, DoStepType, Visit } from '@/types/visit'
import { DO_STEP_SEQUENCE } from './doView'

/** Editable fields of a claim (steps have their own operations). */
export type DoClaimFields = Omit<DoClaim, 'id' | 'steps'>

const OPTIONAL_TEXT = ['reference', 'insurer', 'location', 'comment'] as const
const AMOUNTS = ['claimedAmountCents', 'compensatedAmountCents'] as const

function isValidCents(value: number): boolean {
  return Number.isSafeInteger(value) && value >= 0
}

/**
 * Applies fields: edges trimmed, empty strings removed, blank description
 * refused, invalid dates and amounts ignored (`undefined` clears an amount).
 * @returns `null` when the change is refused.
 */
function applyClaimFields(claim: DoClaim, fields: Partial<DoClaimFields>): DoClaim | null {
  let next = { ...claim }
  if (fields.description !== undefined) {
    const description = fields.description.trim()
    if (!description) return null
    next.description = description
  }
  for (const key of OPTIONAL_TEXT) {
    if (key in fields) next = withOptional(next, key, cleanOptional(fields[key]))
  }
  if ('declaredAt' in fields) {
    const date = cleanOptional(fields.declaredAt)
    if (date === undefined || isValidIsoDate(date)) next = withOptional(next, 'declaredAt', date)
  }
  for (const key of AMOUNTS) {
    if (!(key in fields)) continue
    const amount = fields[key]
    if (amount === undefined || isValidCents(amount)) next = withOptional(next, key, amount)
  }
  return next
}

function mapClaim(
  visit: Visit,
  claimId: string,
  change: (claim: DoClaim) => DoClaim | null,
): Visit {
  const index = visit.doClaims.findIndex((c) => c.id === claimId)
  const current = visit.doClaims[index]
  const next = current && change(current)
  if (!next || next === current) return visit
  return { ...visit, doClaims: visit.doClaims.with(index, next) }
}

function mapStep(
  visit: Visit,
  claimId: string,
  stepId: string,
  change: (step: DoStep) => DoStep,
): Visit {
  return mapClaim(visit, claimId, (claim) => {
    const index = claim.steps.findIndex((s) => s.id === stepId)
    const current = claim.steps[index]
    if (!current) return null
    return { ...claim, steps: claim.steps.with(index, change(current)) }
  })
}

/**
 * Declares a claim with the 10 standard steps, in the order of
 * `DO_STEP_SEQUENCE`, all "À faire". A blank description is ignored (visit
 * returned unchanged); replaying the same creation (same id) does not duplicate.
 *
 * @param input.claimId id of the claim, generated by the caller.
 * @param input.stepIds 10 ids generated by the caller, one per step.
 * @throws {RangeError} if `stepIds` does not hold exactly 10 ids.
 */
export function createDoClaim(
  visit: Visit,
  input: { claimId: string; stepIds: readonly string[]; description: string } & Partial<
    Omit<DoClaimFields, 'description'>
  >,
): Visit {
  const { claimId, stepIds, ...fields } = input
  if (stepIds.length !== DO_STEP_SEQUENCE.length) {
    throw new RangeError(
      `createDoClaim expects ${DO_STEP_SEQUENCE.length} step ids, got ${stepIds.length}`,
    )
  }
  const steps = DO_STEP_SEQUENCE.map((type, i): DoStep => ({
    id: stepIds[i] ?? '',
    type,
    status: 'todo',
  }))
  const created = applyClaimFields({ id: claimId, description: '', steps }, fields)
  if (!created || visit.doClaims.some((c) => c.id === claimId)) return visit
  return { ...visit, doClaims: [...visit.doClaims, created] }
}

/** Updates fields of a claim (see `createDoClaim` for the cleaning rules). */
export function updateDoClaim(
  visit: Visit,
  claimId: string,
  fields: Partial<DoClaimFields>,
): Visit {
  return mapClaim(visit, claimId, (claim) => applyClaimFields(claim, fields))
}

/**
 * Removes a claim.
 * @returns the new visit, plus the removed claim and its index, or
 * `removed: null` when the id is unknown.
 */
export function removeDoClaim(
  visit: Visit,
  claimId: string,
): { visit: Visit; removed: DoClaim | null; index: number } {
  const index = visit.doClaims.findIndex((c) => c.id === claimId)
  const removed = visit.doClaims[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return {
    visit: { ...visit, doClaims: visit.doClaims.filter((c) => c.id !== claimId) },
    removed,
    index,
  }
}

/** Re-inserts a claim at `index` (undo); no-op if already present. */
export function insertDoClaimAt(visit: Visit, claim: DoClaim, index: number): Visit {
  if (visit.doClaims.some((c) => c.id === claim.id)) return visit
  return { ...visit, doClaims: insertAt(visit.doClaims, claim, index) }
}

/**
 * Changes the status of a step. Moving a step to "Terminé" fills its date
 * with `dateIfEmpty` when it has none (an existing date is kept).
 *
 * @param dateIfEmpty today's date, computed by the caller (`todayIso()`).
 */
export function setStepStatus(
  visit: Visit,
  claimId: string,
  stepId: string,
  status: DoStepStatus,
  dateIfEmpty?: string,
): Visit {
  return mapStep(visit, claimId, stepId, (step) => {
    const next = { ...step, status }
    if (status === 'done' && next.date === undefined && dateIfEmpty && isValidIsoDate(dateIfEmpty))
      next.date = dateIfEmpty
    return next
  })
}

/** Updates the date and/or comment of a step (`''` clears; an invalid date is ignored). */
export function updateStep(
  visit: Visit,
  claimId: string,
  stepId: string,
  fields: { date?: string; comment?: string },
): Visit {
  return mapStep(visit, claimId, stepId, (step) => {
    let next = { ...step }
    if ('date' in fields) {
      const date = cleanOptional(fields.date)
      if (date === undefined || isValidIsoDate(date)) next = withOptional(next, 'date', date)
    }
    if ('comment' in fields) next = withOptional(next, 'comment', cleanOptional(fields.comment))
    return next
  })
}

/**
 * Removes a step that does not apply to this claim ("Non applicable").
 * @returns the new visit and the removed step (for "Annuler"), or
 * `removed: null` when the claim or step is unknown.
 */
export function removeStep(
  visit: Visit,
  claimId: string,
  stepId: string,
): { visit: Visit; removed: DoStep | null } {
  const claim = visit.doClaims.find((c) => c.id === claimId)
  const removed = claim?.steps.find((s) => s.id === stepId) ?? null
  if (!removed) return { visit, removed: null }
  return {
    visit: mapClaim(visit, claimId, (c) => ({
      ...c,
      steps: c.steps.filter((s) => s.id !== stepId),
    })),
    removed,
  }
}

/**
 * Re-inserts a removed step at its CANONICAL position: before the first
 * remaining step that comes later in `DO_STEP_SEQUENCE`. Status defaults to
 * "À faire"; pass the removed step's status/date/comment to undo a removal.
 * No-op when the claim already has a step of that type (or that id).
 *
 * @param step.stepId id of the step: the removed step's id, or a new id
 * generated by the caller.
 */
export function restoreStep(
  visit: Visit,
  claimId: string,
  step: { stepId: string; type: DoStepType } & Partial<Pick<DoStep, 'status' | 'date' | 'comment'>>,
): Visit {
  return mapClaim(visit, claimId, (claim) => {
    if (claim.steps.some((s) => s.type === step.type || s.id === step.stepId)) return claim
    const rank = DO_STEP_SEQUENCE.indexOf(step.type)
    const after = claim.steps.findIndex((s) => DO_STEP_SEQUENCE.indexOf(s.type) > rank)
    let restored: DoStep = { id: step.stepId, type: step.type, status: step.status ?? 'todo' }
    restored = withOptional(restored, 'date', step.date)
    restored = withOptional(restored, 'comment', step.comment)
    return {
      ...claim,
      steps: insertAt(claim.steps, restored, after === -1 ? claim.steps.length : after),
    }
  })
}

/** Standard step types missing from a claim (removed as not applicable), in canonical order. */
export function getMissingStepTypes(claim: Pick<DoClaim, 'steps'>): DoStepType[] {
  return DO_STEP_SEQUENCE.filter((type) => !claim.steps.some((step) => step.type === type))
}
