/**
 * Pure operations on `visit.noteSections`. Never mutate; ids are provided by
 * the caller (the autosave replays these functions).
 * Sections are kept in array order with `order` = 0..n-1.
 */
import { moveItem } from '@/lib/objects'
import { normalizeForSearch } from '@/lib/search'
import type { NoteSection, Visit } from '@/types/visit'
import type { NoteTemplate } from './templates'

/** Sections sorted by `order` (the stored order used everywhere). */
export function sortedSections(visit: Visit): NoteSection[] {
  return [...visit.noteSections].sort((a, b) => a.order - b.order)
}

function withSections(visit: Visit, sections: readonly NoteSection[]): Visit {
  return { ...visit, noteSections: sections.map((section, order) => ({ ...section, order })) }
}

/**
 * Appends a section. An empty title is allowed while typing; it falls back to
 * "Nouvelle section" so the visit stays valid.
 */
export function addNoteSection(
  visit: Visit,
  section: { id: string; title?: string; content?: string },
): Visit {
  if (visit.noteSections.some((s) => s.id === section.id)) return visit
  return withSections(visit, [
    ...sortedSections(visit),
    {
      id: section.id,
      title: section.title?.trim() || 'Nouvelle section',
      content: section.content ?? '',
      order: 0,
    },
  ])
}

/**
 * Updates a section title (trimmed; blank titles are refused) and/or content
 * (stored as typed, plain text).
 */
export function updateNoteSection(
  visit: Visit,
  id: string,
  fields: { title?: string; content?: string },
): Visit {
  const index = visit.noteSections.findIndex((s) => s.id === id)
  const section = visit.noteSections[index]
  if (!section) return visit
  const next = { ...section }
  if (fields.title !== undefined && fields.title.trim()) next.title = fields.title.trim()
  if (fields.content !== undefined) next.content = fields.content
  if (next.title === section.title && next.content === section.content) return visit
  return { ...visit, noteSections: visit.noteSections.with(index, next) }
}

/**
 * Removes a section.
 * @returns the new visit, the removed section and its index (for undo).
 */
export function removeNoteSection(
  visit: Visit,
  id: string,
): { visit: Visit; removed: NoteSection | null; index: number } {
  const sections = sortedSections(visit)
  const index = sections.findIndex((s) => s.id === id)
  const removed = sections[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return {
    visit: withSections(
      visit,
      sections.filter((s) => s.id !== id),
    ),
    removed,
    index,
  }
}

/** Moves a section one step up (`-1`) or down (`+1`) and recomputes `order` as 0..n-1. */
export function moveNoteSection(visit: Visit, id: string, direction: -1 | 1): Visit {
  const sections = sortedSections(visit)
  const index = sections.findIndex((s) => s.id === id)
  const target = index + direction
  if (index === -1 || target < 0 || target >= sections.length) return visit
  return withSections(visit, moveItem(sections, index, target))
}

/** Titles of a template not yet present in the visit (accent/case-insensitive). */
export function missingTemplateTitles(visit: Visit, template: NoteTemplate): string[] {
  const present = new Set(visit.noteSections.map((s) => normalizeForSearch(s.title)))
  const missing: string[] = []
  for (const title of template.titles) {
    const key = normalizeForSearch(title)
    if (!present.has(key)) {
      present.add(key)
      missing.push(title)
    }
  }
  return missing
}

/**
 * Appends the template sections that are not already present
 * ("toiture et ETANCHEITE" matches "Toiture et étanchéité").
 *
 * @param ids ids for the new sections, generated by the caller; must contain at
 *   least as many ids as template titles.
 * @returns the new visit and the number of sections added.
 */
export function insertTemplate(
  visit: Visit,
  template: NoteTemplate,
  ids: readonly string[],
): { visit: Visit; added: number } {
  const missing = missingTemplateTitles(visit, template)
  const added = missing.flatMap((title, index) => {
    const id = ids[index]
    return id === undefined ? [] : [{ id, title, content: '', order: 0 }]
  })
  if (added.length === 0) return { visit, added: 0 }
  return { visit: withSections(visit, [...sortedSections(visit), ...added]), added: added.length }
}
