/**
 * Pure operations on `visit.participants`. Never mutate; never generate ids or
 * dates here (they are replayed by the autosave): the caller passes them in.
 */
import { cleanOptional, insertAt, moveItem, withOptional } from '@/lib/objects'
import type { Participant, Visit } from '@/types/visit'

/** Editable fields of a participant. */
export type ParticipantFields = Pick<Participant, 'name' | 'role' | 'company' | 'present'>

function cleanFields(
  participant: Participant,
  fields: Partial<ParticipantFields>,
): Participant | null {
  let next = { ...participant }
  if (fields.name !== undefined) {
    const name = fields.name.trim()
    if (!name) return null
    next.name = name
  }
  if ('role' in fields) next = withOptional(next, 'role', cleanOptional(fields.role))
  if ('company' in fields) next = withOptional(next, 'company', cleanOptional(fields.company))
  if (fields.present !== undefined) next.present = fields.present
  return next
}

/**
 * Appends a participant (present by default). Blank names are ignored.
 * @param participant `id` generated by the caller, outside the updater.
 */
export function addParticipant(
  visit: Visit,
  participant: { id: string; name: string; role?: string; company?: string; present?: boolean },
): Visit {
  const created = cleanFields(
    { id: participant.id, name: '', present: true },
    {
      name: participant.name,
      role: participant.role,
      company: participant.company,
      present: participant.present ?? true,
    },
  )
  if (!created || visit.participants.some((p) => p.id === created.id)) return visit
  return { ...visit, participants: [...visit.participants, created] }
}

/**
 * Updates some fields of a participant (trimmed; empty optional fields are
 * removed). A blank name is refused: the visit is returned unchanged.
 */
export function updateParticipant(
  visit: Visit,
  id: string,
  fields: Partial<ParticipantFields>,
): Visit {
  const index = visit.participants.findIndex((p) => p.id === id)
  const current = visit.participants[index]
  const next = current && cleanFields(current, fields)
  if (!next) return visit
  return { ...visit, participants: visit.participants.with(index, next) }
}

/**
 * Removes a participant.
 * @returns the new visit, plus the removed participant and its index (for
 * "Annuler"), or `removed: null` when the id is unknown.
 */
export function removeParticipant(
  visit: Visit,
  id: string,
): { visit: Visit; removed: Participant | null; index: number } {
  const index = visit.participants.findIndex((p) => p.id === id)
  const removed = visit.participants[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return {
    visit: { ...visit, participants: visit.participants.filter((p) => p.id !== id) },
    removed,
    index,
  }
}

/** Re-inserts a participant at `index` (undo of `removeParticipant`); no-op if already present. */
export function insertParticipantAt(visit: Visit, participant: Participant, index: number): Visit {
  if (visit.participants.some((p) => p.id === participant.id)) return visit
  return { ...visit, participants: insertAt(visit.participants, participant, index) }
}

/** Moves a participant one step up (`-1`) or down (`+1`); no-op at the bounds. */
export function moveParticipant(visit: Visit, id: string, direction: -1 | 1): Visit {
  const index = visit.participants.findIndex((p) => p.id === id)
  const target = index + direction
  if (index === -1 || target < 0 || target >= visit.participants.length) return visit
  return { ...visit, participants: moveItem(visit.participants, index, target) }
}

/** "4 présents · 1 absent" counts. */
export function countPresence(participants: readonly Participant[]): {
  present: number
  absent: number
} {
  const present = participants.filter((p) => p.present).length
  return { present, absent: participants.length - present }
}
