/**
 * Pure operations on `visit.projects`. Never mutate; ids are generated by the
 * caller (the autosave replays these functions).
 *
 * A project is never removed alone: its cost lines are either detached
 * ("Non rattachés") or deleted with it, so no `cost.projectId` is ever left
 * orphan (the visit would not validate).
 */
import { insertCostAt, type RemovedCost } from '@/features/costs/costOps'
import { isValidIsoDate } from '@/lib/dates'
import { cleanOptional, insertAt, withOptional } from '@/lib/objects'
import type { Project, ProjectStatus, Visit } from '@/types/visit'

/** Editable fields of a project. */
export type ProjectFields = Omit<Project, 'id'>

const OPTIONAL_TEXT = ['description', 'owner', 'comment'] as const
const OPTIONAL_DATES = ['startDate', 'endDate'] as const

/**
 * Applies fields: edges trimmed, empty strings removed, blank name refused,
 * invalid dates ignored, end date before start date refused.
 * @returns `null` when the change is refused.
 */
function applyFields(project: Project, fields: Partial<ProjectFields>): Project | null {
  let next = { ...project }
  if (fields.name !== undefined) {
    const name = fields.name.trim()
    if (!name) return null
    next.name = name
  }
  if (fields.status !== undefined) next.status = fields.status
  for (const key of OPTIONAL_TEXT) {
    if (key in fields) next = withOptional(next, key, cleanOptional(fields[key]))
  }
  for (const key of OPTIONAL_DATES) {
    if (!(key in fields)) continue
    const date = cleanOptional(fields[key])
    if (date === undefined || isValidIsoDate(date)) next = withOptional(next, key, date)
  }
  if (next.startDate && next.endDate && next.endDate < next.startDate) return null
  return next
}

/**
 * Appends a project (status "Identifié" by default). A blank name is ignored.
 * @param project `id` generated by the caller, outside the updater.
 */
export function addProject(
  visit: Visit,
  project: { id: string; name: string } & Partial<Omit<ProjectFields, 'name'>>,
): Visit {
  const { id, ...fields } = project
  const created = applyFields(
    { id, name: '', status: 'identified' satisfies ProjectStatus },
    fields,
  )
  if (!created || visit.projects.some((p) => p.id === id)) return visit
  return { ...visit, projects: [...visit.projects, created] }
}

/** Updates fields of a project (see `addProject`); a refused change returns the visit unchanged. */
export function updateProject(visit: Visit, id: string, fields: Partial<ProjectFields>): Visit {
  const index = visit.projects.findIndex((p) => p.id === id)
  const current = visit.projects[index]
  const next = current && applyFields(current, fields)
  if (!next) return visit
  return { ...visit, projects: visit.projects.with(index, next) }
}

/** Re-inserts a project at `index`; no-op if already present. */
export function insertProjectAt(visit: Visit, project: Project, index: number): Visit {
  if (visit.projects.some((p) => p.id === project.id)) return visit
  return { ...visit, projects: insertAt(visit.projects, project, index) }
}

/** What to do with the cost lines of a removed project. */
export type ProjectRemovalMode = 'detach_costs' | 'delete_costs'

/** Everything needed to undo `removeProject` exactly. */
export interface ProjectRemoval {
  mode: ProjectRemovalMode
  project: Project
  index: number
  /** Lines linked to the project: as they were (original `projectId`) and their index. */
  costs: RemovedCost[]
}

/**
 * Removes a project and handles its cost lines:
 * - `detach_costs`: the lines stay, without project ("Non rattachés");
 * - `delete_costs`: the lines are deleted too.
 *
 * @returns the new visit and a snapshot for `restoreProject` (`removed: null`
 * when the id is unknown).
 */
export function removeProject(
  visit: Visit,
  projectId: string,
  mode: ProjectRemovalMode,
): { visit: Visit; removed: ProjectRemoval | null } {
  const index = visit.projects.findIndex((p) => p.id === projectId)
  const project = visit.projects[index]
  if (!project) return { visit, removed: null }
  const costs = visit.costs.flatMap((cost, i) =>
    cost.projectId === projectId ? [{ cost, index: i }] : [],
  )
  const remaining =
    mode === 'delete_costs'
      ? visit.costs.filter((c) => c.projectId !== projectId)
      : visit.costs.map((c) =>
          c.projectId === projectId ? withOptional(c, 'projectId', undefined) : c,
        )
  return {
    visit: {
      ...visit,
      projects: visit.projects.filter((p) => p.id !== projectId),
      costs: remaining,
    },
    removed: { mode, project, index, costs },
  }
}

/**
 * Undoes `removeProject`: puts the project back at its index, then either
 * re-links the detached lines still present, or re-inserts the deleted lines
 * at their former indexes. Right after the removal, the result equals the
 * visit before it.
 */
export function restoreProject(visit: Visit, snapshot: ProjectRemoval): Visit {
  const withProject = insertProjectAt(visit, snapshot.project, snapshot.index)
  if (snapshot.mode === 'delete_costs') {
    return [...snapshot.costs]
      .sort((a, b) => a.index - b.index)
      .reduce((current, { cost, index }) => insertCostAt(current, cost, index), withProject)
  }
  const relink = new Set(snapshot.costs.map(({ cost }) => cost.id))
  return {
    ...withProject,
    costs: withProject.costs.map((cost) =>
      relink.has(cost.id) && cost.projectId === undefined
        ? { ...cost, projectId: snapshot.project.id }
        : cost,
    ),
  }
}
