/**
 * Pure operations on `visit.costs`. Never mutate; ids are generated by the
 * caller (the autosave replays these functions). Display grouping is done by
 * costView; the stored order is the insertion order.
 *
 * Invariant: a cost's `projectId` always references a project of the same
 * visit (otherwise the visit would not validate). An unknown project id is
 * refused; `insertCostAt` drops a link to a project deleted in the meantime.
 */
import { cleanOptional, insertAt, withOptional } from '@/lib/objects'
import type { Cost, CostCategory, CostStatus, Visit } from '@/types/visit'

/** Editable fields of a cost line. */
export type CostFields = Omit<Cost, 'id'>

function isValidCents(value: number): boolean {
  return Number.isSafeInteger(value) && value >= 0
}

function isValidRate(value: number): boolean {
  return Number.isInteger(value) && value >= 0 && value <= 10_000
}

/**
 * Applies fields: edges trimmed, empty strings removed, blank label refused,
 * invalid amount or rate refused, unknown project refused (`projectId:
 * undefined` detaches the line).
 * @returns `null` when the change is refused.
 */
function applyFields(visit: Visit, cost: Cost, fields: Partial<CostFields>): Cost | null {
  let next = { ...cost }
  if (fields.label !== undefined) {
    const label = fields.label.trim()
    if (!label) return null
    next.label = label
  }
  if (fields.category !== undefined) next.category = fields.category
  if (fields.status !== undefined) next.status = fields.status
  if (fields.amountHtCents !== undefined) {
    if (!isValidCents(fields.amountHtCents)) return null
    next.amountHtCents = fields.amountHtCents
  }
  if (fields.vatRateBp !== undefined) {
    if (!isValidRate(fields.vatRateBp)) return null
    next.vatRateBp = fields.vatRateBp
  }
  if ('supplier' in fields) next = withOptional(next, 'supplier', cleanOptional(fields.supplier))
  if ('comment' in fields) next = withOptional(next, 'comment', cleanOptional(fields.comment))
  if ('projectId' in fields) {
    const { projectId } = fields
    if (projectId !== undefined && !visit.projects.some((p) => p.id === projectId)) return null
    next = withOptional(next, 'projectId', projectId)
  }
  return next
}

/**
 * Appends a cost line (category "Travaux", VAT 20 %, status "Estimation" by
 * default). Blank label, invalid amount or unknown project: visit unchanged.
 * @param cost `id` generated by the caller, outside the updater.
 */
export function addCost(
  visit: Visit,
  cost: { id: string; label: string; amountHtCents: number } & Partial<
    Omit<CostFields, 'label' | 'amountHtCents'>
  >,
): Visit {
  const { id, ...fields } = cost
  const base: Cost = {
    id,
    label: '',
    category: 'works' satisfies CostCategory,
    amountHtCents: 0,
    vatRateBp: 2000,
    status: 'estimate' satisfies CostStatus,
  }
  const created = applyFields(visit, base, fields)
  if (!created || visit.costs.some((c) => c.id === id)) return visit
  return { ...visit, costs: [...visit.costs, created] }
}

/** Updates fields of a line (see `addCost`); a refused change returns the visit unchanged. */
export function updateCost(visit: Visit, id: string, fields: Partial<CostFields>): Visit {
  const index = visit.costs.findIndex((c) => c.id === id)
  const current = visit.costs[index]
  const next = current && applyFields(visit, current, fields)
  if (!next) return visit
  return { ...visit, costs: visit.costs.with(index, next) }
}

/**
 * Removes a line.
 * @returns the new visit, plus the removed line and its index (for
 * "Annuler"), or `removed: null` when the id is unknown.
 */
export function removeCost(
  visit: Visit,
  id: string,
): { visit: Visit; removed: Cost | null; index: number } {
  const index = visit.costs.findIndex((c) => c.id === id)
  const removed = visit.costs[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return { visit: { ...visit, costs: visit.costs.filter((c) => c.id !== id) }, removed, index }
}

/**
 * Re-inserts a line at `index` (undo); no-op if already present. If its
 * project no longer exists, the line comes back unassigned (never orphan).
 */
export function insertCostAt(visit: Visit, cost: Cost, index: number): Visit {
  if (visit.costs.some((c) => c.id === cost.id)) return visit
  const safe =
    cost.projectId !== undefined && !visit.projects.some((p) => p.id === cost.projectId)
      ? withOptional(cost, 'projectId', undefined)
      : cost
  return { ...visit, costs: insertAt(visit.costs, safe, index) }
}

/** A removed line and its former index. */
export interface RemovedCost {
  cost: Cost
  index: number
}

/**
 * Removes several lines at once (bulk "Supprimer").
 * @returns the new visit and the removed lines with their indexes, in
 * ascending index order (for `restoreCosts`).
 */
export function removeCosts(
  visit: Visit,
  ids: readonly string[],
): { visit: Visit; removed: RemovedCost[] } {
  const wanted = new Set(ids)
  const removed = visit.costs.flatMap((cost, index) =>
    wanted.has(cost.id) ? [{ cost, index }] : [],
  )
  if (removed.length === 0) return { visit, removed }
  return { visit: { ...visit, costs: visit.costs.filter((c) => !wanted.has(c.id)) }, removed }
}

/** Puts back lines removed by `removeCosts` (or `removeProject`) at their former indexes. */
export function restoreCosts(visit: Visit, removed: readonly RemovedCost[]): Visit {
  return [...removed]
    .sort((a, b) => a.index - b.index)
    .reduce((current, { cost, index }) => insertCostAt(current, cost, index), visit)
}

/**
 * Links lines to a project, or detaches them (`projectId` undefined:
 * "Non rattaché"). An unknown project is refused: visit returned unchanged.
 */
export function moveCostsToProject(
  visit: Visit,
  costIds: readonly string[],
  projectId: string | undefined,
): Visit {
  if (projectId !== undefined && !visit.projects.some((p) => p.id === projectId)) return visit
  const wanted = new Set(costIds)
  const costs = visit.costs.map((cost) =>
    wanted.has(cost.id) && cost.projectId !== projectId
      ? withOptional(cost, 'projectId', projectId)
      : cost,
  )
  return costs.some((cost, i) => cost !== visit.costs[i]) ? { ...visit, costs } : visit
}
