/**
 * Pure operations on `visit.insurances`. Never mutate; ids are generated by
 * the caller (the autosave replays these functions). Display order is
 * computed by insuranceView, the stored order is the insertion order.
 */
import { isValidIsoDate } from '@/lib/dates'
import { cleanOptional, insertAt, withOptional } from '@/lib/objects'
import type { Insurance, InsuranceType, Visit } from '@/types/visit'

/** Editable fields of a contract. */
export type InsuranceFields = Omit<Insurance, 'id'>

const OPTIONAL_TEXT = ['policyNumber', 'broker', 'comment'] as const
const OPTIONAL_DATES = ['startDate', 'endDate'] as const

/**
 * Applies fields: edges trimmed, empty strings removed, blank insurer refused,
 * invalid dates ignored, and a start date after the end date refused (the
 * visit would not validate).
 * @returns `null` when the change is refused.
 */
function applyFields(insurance: Insurance, fields: Partial<InsuranceFields>): Insurance | null {
  let next = { ...insurance }
  if (fields.insurer !== undefined) {
    const insurer = fields.insurer.trim()
    if (!insurer) return null
    next.insurer = insurer
  }
  if (fields.type !== undefined) next.type = fields.type
  for (const key of OPTIONAL_TEXT) {
    if (key in fields) next = withOptional(next, key, cleanOptional(fields[key]))
  }
  for (const key of OPTIONAL_DATES) {
    if (!(key in fields)) continue
    const date = cleanOptional(fields[key])
    if (date === undefined || isValidIsoDate(date)) next = withOptional(next, key, date)
  }
  if (next.startDate && next.endDate && next.endDate < next.startDate) return null
  return next
}

/**
 * Appends a contract. A blank insurer is ignored (visit returned unchanged).
 * @param insurance `id` generated by the caller, outside the updater.
 */
export function addInsurance(
  visit: Visit,
  insurance: { id: string; type: InsuranceType; insurer: string } & Partial<
    Omit<InsuranceFields, 'type' | 'insurer'>
  >,
): Visit {
  const { id, ...fields } = insurance
  const created = applyFields({ id, type: fields.type, insurer: '' }, fields)
  if (!created || visit.insurances.some((i) => i.id === id)) return visit
  return { ...visit, insurances: [...visit.insurances, created] }
}

/**
 * Updates fields of a contract (see `addInsurance` for the cleaning rules).
 * A refused change (blank insurer, end before start) returns the visit unchanged.
 */
export function updateInsurance(visit: Visit, id: string, fields: Partial<InsuranceFields>): Visit {
  const index = visit.insurances.findIndex((i) => i.id === id)
  const current = visit.insurances[index]
  const next = current && applyFields(current, fields)
  if (!next) return visit
  return { ...visit, insurances: visit.insurances.with(index, next) }
}

/**
 * Removes a contract.
 * @returns the new visit, plus the removed contract and its index (for
 * "Annuler"), or `removed: null` when the id is unknown.
 */
export function removeInsurance(
  visit: Visit,
  id: string,
): { visit: Visit; removed: Insurance | null; index: number } {
  const index = visit.insurances.findIndex((i) => i.id === id)
  const removed = visit.insurances[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return {
    visit: { ...visit, insurances: visit.insurances.filter((i) => i.id !== id) },
    removed,
    index,
  }
}

/** Re-inserts a contract at `index` (undo of `removeInsurance`); no-op if already present. */
export function insertInsuranceAt(visit: Visit, insurance: Insurance, index: number): Visit {
  if (visit.insurances.some((i) => i.id === insurance.id)) return visit
  return { ...visit, insurances: insertAt(visit.insurances, insurance, index) }
}
