/** Reusable Zod (`zod/mini`) building blocks shared by the domain schemas. */
import * as z from 'zod/mini'
import { isValidIsoDate, isValidTime } from '@/lib/dates'

/** Entity identifier (UUID generated by `createId()`). */
export const idSchema = z.string().check(z.minLength(1, { error: 'Identifiant manquant' }))

/** Business date `YYYY-MM-DD`. */
export const isoDateSchema = z
  .string()
  .check(z.refine(isValidIsoDate, { error: 'Date invalide (format attendu : AAAA-MM-JJ)' }))

/** Full ISO 8601 timestamp, e.g. `2026-09-28T08:30:00.000Z`. */
export const timestampSchema = z.iso.datetime({
  offset: true,
  error: 'Horodatage invalide (ISO 8601 attendu)',
})

/** Time of day `HH:mm`. */
export const timeSchema = z
  .string()
  .check(z.refine(isValidTime, { error: 'Heure invalide (format attendu : HH:mm)' }))

/** Safe integer; `message` is used when the input is a number that is not an integer. */
function integer(notIntegerMessage: string, invalidMessage: string) {
  return z.int({
    error: (issue) =>
      typeof issue.input === 'number' && Number.isFinite(issue.input)
        ? Number.isSafeInteger(Math.trunc(issue.input))
          ? notIntegerMessage
          : 'Valeur trop élevée'
        : invalidMessage,
  })
}

/** Amount in integer cents, ≥ 0. */
export const centsSchema = integer(
  'Le montant doit être un nombre entier de centimes',
  'Montant invalide',
).check(z.nonnegative({ error: 'Le montant ne peut pas être négatif' }))

/** VAT rate in basis points (2000 = 20 %), between 0 and 100 %. */
export const vatRateBpSchema = integer(
  'Le taux de TVA doit être exprimé en points de base entiers',
  'Taux de TVA invalide',
).check(
  z.nonnegative({ error: 'Le taux de TVA ne peut pas être négatif' }),
  z.lte(10_000, { error: 'Le taux de TVA ne peut pas dépasser 100 %' }),
)

/** Non-negative integer (sort order…). */
export const orderSchema = integer('L’ordre doit être un entier', 'Ordre invalide').check(
  z.nonnegative({ error: 'L’ordre ne peut pas être négatif' }),
)

/** Required, non-blank single-line text (trimmed). */
export function requiredText(label: string, max = 200) {
  return z
    .string({ error: `${label} est obligatoire` })
    .check(
      z.trim(),
      z.minLength(1, { error: `${label} est obligatoire` }),
      z.maxLength(max, { error: `${label} ne doit pas dépasser ${max} caractères` }),
    )
}

/** Optional free text. */
export function optionalText(max = 500) {
  return z.optional(
    z
      .string()
      .check(z.maxLength(max, { error: `Ce texte ne doit pas dépasser ${max} caractères` })),
  )
}

/** Long multi-line free text (notes, comments). */
export const LONG_TEXT_MAX = 50_000

/**
 * Check "endDate ≥ startDate when both are set" for an object schema
 * (ISO dates compare correctly as strings).
 */
export const dateRangeCheck = z.superRefine(
  (value: { startDate?: string | undefined; endDate?: string | undefined }, ctx) => {
    if (value.startDate && value.endDate && value.endDate < value.startDate) {
      ctx.addIssue({
        code: 'custom',
        path: ['endDate'],
        message: 'La date de fin doit être postérieure ou égale à la date de début',
        input: value.endDate,
      })
    }
  },
)
