/**
 * User guide: SINGLE SOURCE of the in-app help dialog and of
 * docs/GUIDE_UTILISATEUR.md (generated by `npm run guide`, see
 * scripts/generate-guide.ts). No import here: the file is read directly by
 * Node (type stripping) as well as bundled in the app.
 *
 * Inline formatting: **bold** and `key` (keyboard key or button name).
 */

export type GuideBlock =
  | { type: 'p'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }

export interface GuideSection {
  id: string
  title: string
  blocks: GuideBlock[]
}

export const GUIDE_TITLE = 'Guide utilisateur — Comptes rendus de visite'

export const GUIDE_INTRO =
  'Outil de comptes rendus de visites techniques et de réunions pour les Property Managers de Carrefour Property. Il fonctionne sans Internet et sans installation : tout reste sur votre poste.'

export const GUIDE_SECTIONS: GuideSection[] = [
  {
    id: 'start',
    title: '1. Démarrer',
    blocks: [
      {
        type: 'list',
        items: [
          '**Ouvrir l’outil** : double-cliquez sur le fichier `CR-Visites-Carrefour-Property-v1.0.0.html`. Il s’ouvre dans votre navigateur, sans connexion Internet.',
          '**Navigateur** : **Google Chrome** ou **Microsoft Edge** uniquement. Utilisez toujours **le même** navigateur : vos visites y sont enregistrées.',
          '**Créer une visite** : bouton `Nouvelle visite`, choisissez « Visite technique » ou « Réunion », puis le titre, la date et le site.',
          'Tout est **enregistré automatiquement** : l’indicateur « Enregistré » s’affiche en haut à droite de la visite.',
        ],
      },
    ],
  },
  {
    id: 'during',
    title: '2. Pendant et après la visite',
    blocks: [
      {
        type: 'list',
        items: [
          '**Informations générales** : rédacteur, objet, site, participants (cochez « Présent » ou non). Tapez le nom puis `Entrée` pour ajouter le participant suivant.',
          '**Notes** : une section par zone (toiture, quais, sprinklage…). `Insérer la trame visite technique` crée les sections usuelles. Une ligne commençant par « - » devient une puce dans le rapport. `Lier des photos` associe des photos à la zone : elles apparaissent sous ses observations dans le rapport.',
          '**Points d’attention** : saisissez l’action, la priorité, le responsable et l’échéance, puis `Entrée`. Les points en retard sont signalés en rouge.',
          '**Photos** : glissez les photos sur l’onglet ou `Ajouter des photos`. Ajoutez une légende et une catégorie (désordre, sécurité…).',
          '**Photos d’iPhone (HEIC)** : non prises en charge. Sur l’iPhone : **Réglages › Appareil photo › Formats › « Le plus compatible »**, ou partagez la photo en JPEG.',
          '**Plan** : depuis AutoCAD, « Tracer » ou « Exporter » en **PDF** (ou en **PNG**), puis `Importez le plan`. Pour un PDF de plusieurs pages, choisissez la page.',
        ],
      },
      { type: 'p', text: '**Placer une photo sur le plan**, au choix :' },
      {
        type: 'list',
        items: [
          '**glisser** la miniature du panneau de droite et la **déposer** sur le plan ;',
          '**cliquer** sur la miniature, puis **cliquer** sur le plan à l’endroit voulu (`Échap` pour annuler) ;',
          '**au clavier** : `Entrée` sur la miniature, puis `Entrée` sur le plan (le repère est posé au centre de la vue).',
        ],
      },
      {
        type: 'p',
        text: 'Chaque photo a un seul repère numéroté ; le replacer le déplace. Cliquez sur un repère pour lui donner une étiquette ou le retirer.',
      },
    ],
  },
  {
    id: 'follow-up',
    title: '3. Suivre un site d’une visite à l’autre',
    blocks: [
      {
        type: 'p',
        text: 'Pour la visite suivante du même site, **dupliquez** la visite : menu `⋯` de la visite, puis `Dupliquer`. La copie est datée du jour.',
      },
      {
        type: 'table',
        headers: ['Repris dans la copie', 'Non repris'],
        rows: [
          ['Site et participants (marqués absents)', 'Photos et repères'],
          [
            'Notes par zone (case « Garder les notes », cochée par défaut)',
            'Points d’attention terminés',
          ],
          ['Points d’attention non terminés', 'Photo de la page de garde'],
          ['Sinistres DO, contrats d’assurance', ''],
          ['Projets et coûts, plans', ''],
        ],
      },
      {
        type: 'p',
        text: 'La visite d’origine ne change pas : elle garde l’état du dossier à sa date.',
      },
    ],
  },
  {
    id: 'do-costs',
    title: '4. DO, assurances, projets et coûts',
    blocks: [
      {
        type: 'list',
        items: [
          '**Saisie rapide** : dans chaque tableau, remplissez la ligne du haut puis `Entrée`. Tout se modifie ensuite directement dans le tableau ; une suppression peut être annulée (`Annuler` dans le message).',
          '**Sinistre DO** : `Déclarer un sinistre` crée les 10 étapes, de la déclaration à la clôture. Passez chaque étape à « Terminé » au fur et à mesure ; `Non applicable` retire une étape.',
          '**Délais** : l’outil calcule les échéances de l’assureur (position sur la garantie à 60 jours, proposition d’indemnité à 90 jours) à partir de l’accusé de réception, ou à défaut de la déclaration. **Ces délais sont indicatifs** (art. L242-1 du Code des assurances) : vérifiez-les toujours sur le contrat.',
          '**Contrats** : la validité s’affiche (« Expire dans 23 j » en orange, « Expiré » en rouge).',
          '**Coûts** : montant HT et taux de TVA ; la TVA et le TTC sont calculés. Les totaux sont donnés par stade : estimation, devis reçu, engagé, facturé.',
          '`Copier pour Excel` copie tout le tableau des coûts : collez-le dans Excel avec `Ctrl+V`. Si la copie est impossible, un fichier CSV est téléchargé à la place.',
        ],
      },
    ],
  },
  {
    id: 'report',
    title: '5. Générer le rapport Word',
    blocks: [
      {
        type: 'list',
        items: [
          'Onglet **Rapport** : cochez les rubriques voulues (les rubriques vides sont omises).',
          '**Page de garde** : `Choisir la photo de garde` place une photo du site (l’entrepôt, la façade…) sous le titre du rapport.',
          'Choisissez **6, 4 ou 2 photos par page** et la qualité des images : **Allégée** pour un envoi par mail.',
          'Les **points à vérifier** (photos sans légende, rédacteur manquant…) ne bloquent pas : cliquez dessus pour les corriger.',
          '`Générer le rapport Word` : le fichier « CR - site - date.docx » est téléchargé. Ouvrez-le dans Word pour le relire ou le compléter.',
          'Le rapport est **la seule copie durable** de la visite : enregistrez-le sur le réseau ou dans le dossier du site.',
        ],
      },
    ],
  },
  {
    id: 'data',
    title: '6. Vos données',
    blocks: [
      {
        type: 'list',
        items: [
          'Les visites sont enregistrées **dans le navigateur de ce poste uniquement** : elles ne sont ni sur Internet, ni sur un serveur, ni sur un autre ordinateur.',
          '**Ne videz pas les données de navigation** (« Cookies et autres données de site ») : vos visites seraient effacées. Évitez aussi la navigation privée.',
          '**Générez le rapport Word** de chaque visite terminée : c’est votre archive.',
          '**Nouvelle version de l’outil** : remplacez simplement l’ancien fichier HTML par le nouveau ; vos visites sont conservées, tant que vous utilisez le même navigateur sur le même poste.',
          '**Changement de poste** : les visites ne suivent pas. Avant le changement, générez les rapports Word des visites en cours et conservez-les.',
          '**Espace bientôt plein** (message en bas de page) : générez les rapports, puis supprimez les anciennes visites.',
        ],
      },
    ],
  },
  {
    id: 'shortcuts',
    title: '7. Raccourcis clavier',
    blocks: [
      {
        type: 'table',
        headers: ['Où', 'Touche', 'Action'],
        rows: [
          ['Saisies rapides', '`Entrée`', 'Ajouter la ligne'],
          ['Onglets', '`←` `→`', 'Onglet précédent / suivant'],
          ['Galerie photos', '`Alt+←` `Alt+→`', 'Déplacer la photo sélectionnée'],
          ['Galerie photos', '`Ctrl+A` / `Ctrl+V`', 'Tout sélectionner / coller une image'],
          ['Visionneuse', '`←` `→` / `Échap`', 'Photo précédente, suivante / fermer'],
          ['Plan', '`+` `-` / `0`', 'Zoomer, dézoomer / ajuster'],
          ['Plan', '`↑` `↓` `←` `→`', 'Déplacer la vue'],
          ['Repère sélectionné', 'flèches (`Maj` : plus loin)', 'Déplacer le repère'],
          ['Repère sélectionné', '`Suppr`', 'Retirer le repère'],
          ['Placement d’une photo', '`Échap`', 'Annuler'],
        ],
      },
    ],
  },
]

/** Escapes the characters meaningful in a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

/**
 * The guide as Markdown (docs/GUIDE_UTILISATEUR.md). Same content and order
 * as the help dialog.
 */
export function guideToMarkdown(sections: readonly GuideSection[] = GUIDE_SECTIONS): string {
  const lines: string[] = [
    `# ${GUIDE_TITLE}`,
    '',
    '<!-- Fichier généré par `npm run guide` depuis src/features/help/guideContent.ts : ne pas modifier à la main. -->',
    '',
    GUIDE_INTRO,
    '',
  ]
  for (const section of sections) {
    lines.push(`## ${section.title}`, '')
    for (const block of section.blocks) {
      if (block.type === 'p') lines.push(block.text, '')
      else if (block.type === 'list') lines.push(...block.items.map((item) => `- ${item}`), '')
      else {
        lines.push(
          `| ${block.headers.map(cell).join(' | ')} |`,
          `| ${block.headers.map(() => '---').join(' | ')} |`,
          ...block.rows.map((row) => `| ${row.map(cell).join(' | ')} |`),
          '',
        )
      }
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}
