/**
 * Pure operations on `visit.pins` (replayed by the autosave: no ids, dates or
 * randomness here — `pinId` is generated by the caller).
 *
 * Rule: ONE photo has AT MOST ONE pin. Placing an already placed photo moves
 * its pin (plan and position) and keeps its number. Numbers come from
 * `visit.nextPinNumber` and are never reassigned, even after a removal.
 */
import { insertAt } from '@/lib/objects'
import type { Pin } from '@/types/media'
import type { Visit } from '@/types/visit'
import { allocatePinNumber } from './pins'

/** Clamps a normalized coordinate to [0, 1]. */
export function clamp01(value: number): number {
  if (Number.isNaN(value)) return 0.5
  return Math.min(1, Math.max(0, value))
}

/**
 * Places a photo on a plan at (x, y) (normalized 0–1).
 * - Photo without pin: a new pin is created with the next number (`allocatePinNumber`).
 * - Photo already placed: its pin is moved (plan + position), number kept, counter unchanged.
 *
 * @param placement `pinId` is only used for a new pin (generated by the caller).
 * @returns the new visit, the resulting pin and whether an existing pin was moved.
 */
export function placePhotoOnPlan(
  visit: Visit,
  placement: { pinId: string; planId: string; photoId: string; x: number; y: number },
): { visit: Visit; pin: Pin; moved: boolean } {
  const x = clamp01(placement.x)
  const y = clamp01(placement.y)
  const index = visit.pins.findIndex((pin) => pin.photoId === placement.photoId)
  const existing = visit.pins[index]
  if (existing) {
    const pin = { ...existing, planId: placement.planId, x, y }
    return { visit: { ...visit, pins: visit.pins.with(index, pin) }, pin, moved: true }
  }
  const { number, visit: allocated } = allocatePinNumber(visit)
  const pin: Pin = {
    id: placement.pinId,
    planId: placement.planId,
    photoId: placement.photoId,
    x,
    y,
    number,
  }
  return { visit: { ...allocated, pins: [...allocated.pins, pin] }, pin, moved: false }
}

function updatePin(visit: Visit, pinId: string, change: (pin: Pin) => Pin): Visit {
  const index = visit.pins.findIndex((pin) => pin.id === pinId)
  const pin = visit.pins[index]
  if (!pin) return visit
  const next = change(pin)
  if (next.x === pin.x && next.y === pin.y && next.label === pin.label) return visit
  return { ...visit, pins: visit.pins.with(index, next) }
}

/** Moves a pin to (x, y), clamped to [0, 1]. */
export function movePin(visit: Visit, pinId: string, x: number, y: number): Visit {
  return updatePin(visit, pinId, (pin) => ({ ...pin, x: clamp01(x), y: clamp01(y) }))
}

/** Moves a pin by (dx, dy) in normalized units (0.005 = 0.5 %), clamped to [0, 1]. */
export function nudgePin(visit: Visit, pinId: string, dx: number, dy: number): Visit {
  return updatePin(visit, pinId, (pin) => ({
    ...pin,
    x: clamp01(pin.x + dx),
    y: clamp01(pin.y + dy),
  }))
}

/** Sets the pin's own label (trimmed; empty removes it). */
export function setPinLabel(visit: Visit, pinId: string, label: string): Visit {
  const trimmed = label.trim()
  return updatePin(visit, pinId, (pin) => {
    const { label: _previous, ...rest } = pin
    return trimmed ? { ...rest, label: trimmed } : rest
  })
}

/**
 * Removes a pin. Its number is NOT freed (`nextPinNumber` unchanged).
 * @returns the new visit, the removed pin and its index (for "Annuler").
 */
export function removePin(
  visit: Visit,
  pinId: string,
): { visit: Visit; removed: Pin | null; index: number } {
  const index = visit.pins.findIndex((pin) => pin.id === pinId)
  const removed = visit.pins[index]
  if (!removed) return { visit, removed: null, index: -1 }
  return { visit: { ...visit, pins: visit.pins.filter((pin) => pin.id !== pinId) }, removed, index }
}

/**
 * Re-inserts a removed pin with its number and position (undo of `removePin`).
 * No-op if the photo got another pin meanwhile (one photo, one pin).
 */
export function restorePin(visit: Visit, pin: Pin, index: number): Visit {
  if (visit.pins.some((p) => p.id === pin.id || p.photoId === pin.photoId)) return visit
  return { ...visit, pins: insertAt(visit.pins, pin, index) }
}
